version: "3.8"

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/mydatabase
    depends_on:
      - mongo_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo_db:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
